version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: agrolocal_db
    restart: always
    environment:
      - POSTGRES_USER=agrolocal_user
      - POSTGRES_PASSWORD=agrolocal_pass
      - POSTGRES_DB=agrolocal
    ports:
      - "5434:5432" # <--- MUDAR AQUI (A porta externa não deve ser igual as anteriores)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
