"""Initial Schema Postgres UUID

Revision ID: eb75e491a71b
Revises: 
Create Date: 2026-02-18 17:23:56.515074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.database


# revision identifiers, used by Alembic.
revision: str = 'eb75e491a71b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PRODUTOR', 'CLIENTE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('address_type', sa.Enum('RESIDENCIAL', 'COMERCIAL', 'RURAL', 'PONTO_ENCONTRO', name='addresstype'), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=150), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=9), nullable=False),
    sa.Column('reference_point', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'SYSTEM_EVENT', name='auditaction'), nullable=False),
    sa.Column('actor_id', app.core.database.GUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_table('global_products',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=True),
    sa.Column('synonyms', sa.String(length=255), nullable=True),
    sa.Column('category_id', app.core.database.GUID(), nullable=False),
    sa.Column('taxonomy_code', sa.String(length=50), nullable=True),
    sa.Column('ncm_code', sa.String(length=8), nullable=True),
    sa.Column('description_template', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ARCHIVED', name='productstatus'), nullable=False),
    sa.Column('suggested_by_id', app.core.database.GUID(), nullable=True),
    sa.Column('reviewed_by_id', app.core.database.GUID(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suggested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_products_id'), 'global_products', ['id'], unique=False)
    op.create_index(op.f('ix_global_products_name'), 'global_products', ['name'], unique=True)
    op.create_index(op.f('ix_global_products_synonyms'), 'global_products', ['synonyms'], unique=False)
    op.create_table('orders',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('customer_id', app.core.database.GUID(), nullable=False),
    sa.Column('producer_id', app.core.database.GUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAID', 'CONFIRMED', 'PREPARING', 'READY', 'IN_TRANSIT', 'DELIVERED', 'CANCELED', 'REFUSED', name='orderstatus'), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_type', sa.Enum('RETIRADA', 'PONTO_ENCONTRO', 'DOMICILIO', name='deliverytype'), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_address_snapshot', sa.Text(), nullable=True),
    sa.Column('platform_fee_percentage', sa.Float(), nullable=True),
    sa.Column('platform_fee_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('producer_net_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_producer_id'), 'orders', ['producer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('producer_profiles',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('user_id', app.core.database.GUID(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('pix_key', sa.String(length=100), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_producer_profiles_cpf_cnpj'), 'producer_profiles', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_producer_profiles_id'), 'producer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_producer_profiles_store_name'), 'producer_profiles', ['store_name'], unique=False)
    op.create_table('payouts',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('order_id', app.core.database.GUID(), nullable=False),
    sa.Column('producer_id', app.core.database.GUID(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED', name='payoutstatus'), nullable=True),
    sa.Column('amount_gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_pix_key_snapshot', sa.String(length=100), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bank_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('proof_url', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['producer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_payouts_bank_transaction_id'), 'payouts', ['bank_transaction_id'], unique=True)
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_table('producer_products',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('producer_id', app.core.database.GUID(), nullable=False),
    sa.Column('global_product_id', app.core.database.GUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('stock_quantity', sa.Float(), nullable=True),
    sa.Column('availability_type', sa.Enum('PRONTA_ENTREGA', 'ENCOMENDA', name='availabilitytype'), nullable=True),
    sa.Column('minimum_order_quantity', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['global_product_id'], ['global_products.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['producer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_products_id'), 'producer_products', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('author_id', app.core.database.GUID(), nullable=False),
    sa.Column('producer_id', app.core.database.GUID(), nullable=False),
    sa.Column('order_id', app.core.database.GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['producer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('order_id', app.core.database.GUID(), nullable=False),
    sa.Column('payment_method', sa.Enum('PIX', 'CREDIT_CARD', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'FAILED', 'REFUNDED', 'EXPIRED', name='transactionstatus'), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('pix_qr_code_base64', sa.Text(), nullable=True),
    sa.Column('pix_copy_paste', sa.Text(), nullable=True),
    sa.Column('pix_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_transactions_external_transaction_id'), 'transactions', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('order_id', app.core.database.GUID(), nullable=False),
    sa.Column('product_id', app.core.database.GUID(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=20), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['producer_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', app.core.database.GUID(), nullable=False),
    sa.Column('producer_product_id', app.core.database.GUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['producer_product_id'], ['producer_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_producer_products_id'), table_name='producer_products')
    op.drop_table('producer_products')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_bank_transaction_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_producer_profiles_store_name'), table_name='producer_profiles')
    op.drop_index(op.f('ix_producer_profiles_id'), table_name='producer_profiles')
    op.drop_index(op.f('ix_producer_profiles_cpf_cnpj'), table_name='producer_profiles')
    op.drop_table('producer_profiles')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_producer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_global_products_synonyms'), table_name='global_products')
    op.drop_index(op.f('ix_global_products_name'), table_name='global_products')
    op.drop_index(op.f('ix_global_products_id'), table_name='global_products')
    op.drop_table('global_products')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
